messages:
- "&c&lWelcome to &6&lBusinessCraft! &a&lIf you have any questions, do not be shy to ask in chat!"
- "&b&lHey there! &a&lWelcome to &6&lBusinessCraft!"
- "&5&lWelcome to &6&lBC! &3&lIf you have any questions just ask!"
- "&d&lHello! &9&lWelcome to Businesscraft! &a&lLet us know if you have any questions!"